{% set name = "skan" %}
{% set version = "0.6.1" %}
{% set sha256 = "45012b17d078d93723b8ee966d977ee625bf90c2d2ed4983a32dd478a0619a1e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip : True  # [py<36]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.11
    - scipy >=0.18
    - networkx >=1.11
    - pandas >=0.18
    - openpyxl>=2.4
    - xlrd>=1.0
    - numba >=0.29
    - matplotlib >=1.5
    - scikit-image >=0.12
    - imageio >=2.0
    - tqdm >=4.11
    - nose >=1.3
    - click >=0.5

test:
  requires:
    - pytest
    - hypothesis
  imports:
    - skan
  commands:
    - py.test --pyargs skan --doctest-modules

about:
  home: http://github.com/jni/skan
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'skan: skeleton analysis in Python'

  description: |
    skan: skeleton analysis in Python.

    Inspired by the "Analyze skeletons" Fiji plugin by
    Ignacio Arganda-Carreras.
  doc_url: https://github.com/jni/skan
  dev_url: https://github.com/jni/skan

extra:
  recipe-maintainers:
    - jni
