{% set version = "0.13.0" %}
{% set python_min = "3.9" %}

package:
  name: skan
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/skan/skan-{{ version }}.tar.gz
  sha256: 0c184a369c391b89bfbac919f78c0c89f1e39c56a4aecd7be9322f6d046ad762

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - imageio >=2.10.1
    - magicgui >=0.7.3
    - matplotlib-base >=3.4
    - networkx >=2.7
    - numba >=0.58
    - numpy >=1.25
    - openpyxl >=2.6
    - pandas >=2.0.2
    - scikit-image >=0.17.1
    - scipy >=1.7
    - toolz >=0.10.0
    - tqdm >=4.57.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - skan

about:
  home: http://github.com/jni/skan
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'skan: skeleton analysis in Python'

  description: |
    skan: skeleton analysis in Python.

    Inspired by the "Analyze skeletons" Fiji plugin by
    Ignacio Arganda-Carreras.
  doc_url: https://jni.github.io/skan
  dev_url: https://github.com/jni/skan

extra:
  recipe-maintainers:
    - jni
