{% set version = "0.9" %}

package:
  name: skan
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/skan/skan-{{ version }}.tar.gz
  sha256: 41a263bd925365ff2ad86d9841e9e65259af7bce3f95504983a0af56b1a26b9d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - skan-gui = skan.gui:launch

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.11
    - scipy >=0.18
    - networkx >=1.11
    - pandas >=0.18
    - openpyxl >=2.4
    - xlrd >=1.0
    - numba >=0.29
    - matplotlib-base >=1.5
    - scikit-image >=0.12
    - imageio >=2.0
    - tqdm >=4.11
    - nose >=1.3
    - click >=0.5

test:
  imports:
    - skan

about:
  home: http://github.com/jni/skan
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'skan: skeleton analysis in Python'

  description: |
    skan: skeleton analysis in Python.

    Inspired by the "Analyze skeletons" Fiji plugin by
    Ignacio Arganda-Carreras.
  doc_url: https://jni.github.io/skan
  dev_url: https://github.com/jni/skan

extra:
  recipe-maintainers:
    - jni
