{% set version = "0.10.0" %}

package:
  name: skan
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/skan/skan-{{ version }}.tar.gz
  sha256: 60554873e9115e3b8e22120514d1c9cef45f5660193c455401f197b0da652a59

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.16.5
    - scipy >=1.2.0
    - networkx >=2.0
    - pandas >=1.0
    - openpyxl >=2.4
    - numba >=0.50
    - matplotlib-base >=3.0
    - scikit-image >=0.17
    - imageio >=2.0
    - tqdm >=4.56.0
    - toolz >=0.10.0

test:
  imports:
    - skan

about:
  home: http://github.com/jni/skan
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'skan: skeleton analysis in Python'

  description: |
    skan: skeleton analysis in Python.

    Inspired by the "Analyze skeletons" Fiji plugin by
    Ignacio Arganda-Carreras.
  doc_url: https://jni.github.io/skan
  dev_url: https://github.com/jni/skan

extra:
  recipe-maintainers:
    - jni
