travis:
  secure:
    BINSTAR_TOKEN: eABI87raCrqv0M3/5sTf9Wic6mpSaI5QmL9V4e3EKjr0j239D4DwcmutB/HsvB97kj1GUVf3c0Xspvc58tSPAZHUbAAMxlr0+50FS3FqNgPbrcSe9/lOInB1xatWQqd+z9S+y0bBKJUkisLa6RV8qMIsBa5kK/Ot6eBmsoP3pJwqbXEpoYNatcXc6MPhdV8rce7DxHQCvOBJ1R3WYWcRjp/ubptkNy+WW2KirMKmV1tarcJyGmREsjYgOOeqZi90915H9UljfG/wo4kJcXaL5PmAO+icOjd70nbXrp2kAM3dYQ8gzm736JP2RgmPgRkzE2vu+TbDpXfV2vRiQGTFv28OhDwCe085L00t/PbWTjSe+p4R9nrCt1gtxDEziyqE9+x9B55d89RAw3dkBxM8+WW4EIVlQM+F1FTvS6Qa8V2l14UhOcW/3mEvPbL5fZ3tuzBtJlEfY00Q8a0He25TARrGs6LPNzbX9nNSnMtUbzKsfOBXaqcteBod5A2rOoAKDf65bkQO4XL7FRC7B/8Gyxrioex2T8UYarFG3O0PYufNXKAmrEc+mg16NUC2mNbR5JL1gYwQKI0TDD9LGTUebABcKqrYaZtvcJHGR18ITzDPrY3x5ByH1nFGT4uFgIRx/ARSOXx+NxLgQAAoG0nYLqD4pgQfJJLmoMHMkScKDDk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
