travis:
  secure:
    BINSTAR_TOKEN: DtZeflEOTBUKgAgUMFda+wr/VI5hnJB50FBUsaqAk3g+bo5QQjPUuNwMfOuEEtkTjHgzXMK+6MMzdwye2GkcpiIo+SsROrb3B0vTbjFjgKT9U9fQ+c9hXNqnZJC4+NP4eK7Xfvf5W/6W7lb5EmWKapy2f/ckxM8tcf4mdpCLW3f64bO0yOLmnIl+bd+RD/UcxcXUn+y9walXZpg9RnJ2i4dsMtY5gnis+4twTrShVqWwkich3T2OxTtp6UzaCqGoXijAWMQcFoPY/ZwDy+eboXRrKCXByZ7Ii2VnLBTJDw9shmruPB015ERro1X7aI5OZw9o8Qmvr4k5KCighnQnO9dyEokizzho0RU8TC+0BL2X1sHDx3a8RrQQlGPL4hGASRd5i7LCKn+VL41cvulo6R5RUrZCZVBAQ8PKCdfDTFkL6YzbcKvp/OwjLCLTHwAxNNKPr3OFPmuIu5I8y+XbNTgLCsw06kU4GRWvzTfhCwiRXjv5eQHGmeQ3cU2NDbLlDehmEXL2RpRGzBF4KqDnqMx6rVy64v6GuWjGm0pAoXhML0vmqc1msOQH1O2/bLl02oWMiHUekTD+kgvo+Gc6Z8y3IjxvgvrBUIo97Tk6/WV/Gm4dt1pOpTYCMp9SmUuWd4PcDx/RC5GH9BHHNm1vCJI6YR7zE6ig/LDMHztiX1I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
